[workspace]
members = [
    "runner",
    "day1",
    "day2",
    "day3",
    "day4",
    "day5",
    "day6",
    "day7",
    "day8",
    "day9",
    "day10",
    "day11"
]
resolver = "2"

[workspace.dependencies]
itertools = "0.12.0"
counter = "0.5.7"
